# Generated by Django 3.2.9 on 2021-12-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaclinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('idR', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Paciente')),
                ('fecha', models.DateField(max_length=10, verbose_name='fecha')),
                ('edad', models.CharField(max_length=10, verbose_name='Edad')),
                ('nombreD', models.CharField(max_length=100, verbose_name='Nombre Doctor')),
                ('sexo', models.CharField(max_length=10, verbose_name='Sexo')),
                ('enfermedad', models.CharField(max_length=200, verbose_name='Enfermedad')),
                ('medicamento', models.CharField(max_length=100, verbose_name='Medicamento')),
            ],
        ),
    ]
