# Generated by Django 3.2.9 on 2021-12-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaclinica', '0004_inventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('idC', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fechac', models.DateField(max_length=10, verbose_name='Fecha')),
                ('hora', models.DateTimeField(max_length=10, verbose_name='Hora')),
                ('motivo', models.CharField(max_length=100, verbose_name='Motivo de consulta')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
            ],
        ),
    ]
