# Generated by Django 3.2.9 on 2021-12-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaclinica', '0005_citas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='hora',
            field=models.TimeField(max_length=10, verbose_name='Hora'),
        ),
    ]
