# Generated by Django 3.2.9 on 2021-12-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaclinica', '0009_alter_citas_fechac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='hora',
            field=models.CharField(max_length=10, verbose_name='Hora'),
        ),
    ]
