# Generated by Django 3.2.9 on 2021-12-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaclinica', '0011_alter_citas_fechac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('idE', models.AutoField(primary_key=True, serialize=False)),
                ('nombree', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cargo', models.CharField(max_length=30, verbose_name='Cargo')),
                ('sexoe', models.CharField(max_length=10, verbose_name='Sexo')),
                ('direccione', models.CharField(max_length=100, verbose_name='Direccion')),
            ],
        ),
    ]
