# Generated by Django 3.2.9 on 2021-12-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaclinica', '0012_empleados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('idM', models.AutoField(primary_key=True, serialize=False)),
                ('nombreem', models.CharField(max_length=100, verbose_name='Nombre del medicamento')),
                ('presentacion', models.CharField(max_length=30, verbose_name='Presentacion')),
                ('cantidad', models.CharField(max_length=10, verbose_name='Cantidad')),
                ('viaadministracion', models.CharField(max_length=100, verbose_name='Via de administracion')),
            ],
        ),
    ]
